### ISSUE TITLE
(20127597_Bùi Tấn Phương) Góp ý đồ án

### ISSUE THREAD

**Issue by PhuongBui712** [bovip1822002/Project-Programming-DS#4]
1. Ở phần **Type of each column** mình thấy nhóm bạn có chuyển kiểu dữ liệu của cột "year of production" về kiểu `object` nhưng sau đó bạn lại chuyển về kiểu `np.number` ở trong class `preprocess`, mình nghĩ nếu bạn không chuyển về kiểu `object` mà để nguyên thì sẽ không phải chuyển đi chuyển lại tốn chi phí.
2. Ở gạch đầu dòng cuối cùng, mình có thấy nhóm bạn viết sai từ ("columns" -> "coloumns") và bạn có kết luận rằng: "Finally, In each model, for categorical coloumns we fill nan with its median and for numerical coloumns we fill with its means". Mình không hiểu ý nghĩa của việc điền vào chỗ trống của cột categorical bằng giá trị median, categorical thì làm sao tính được median ạ?
3. Cũng ở câu hỏi số 1, mình thầy bạn đưa ra mô hình là dự đoán giá của đồng Rolex nhưng câu hỏi của bạn là làm sao để biết là nào là một cuộc mua bán tốt. Bạn không giải thích rõ thế nào là cuộc mua bán tốt khi mà dự đoạn xong giá của sample
4. Cuối cùng là mình thấy độ chính xác của mô hình của bạn là thấy (trên 60% khi test), mình nghĩ bạn nên cải thiện mô hình bằng các thử nhiều mô hình Regression khác hay là tối ưu mô hình bằng **feature selection** hay là **tuning hyperparameter**

**Comment by baonhat1802** [comment]
Cám ơn nha ❤️

**Comment by baonhat1802** [comment]
Tui có thử stack nhiều model lại để mong tăng accuracy với có thử xài SelectKBest luôn rồi nó chạy cho 4-5 tiếng mà tăng có 1-2% accuracy nên thôi tui giữ nguyên luôn á. Ông có gợi ý gì tụi tui không ? Cám ơn ông nhiều nha

**Comment by nthng-quan** [comment]
Cảm ơn bạn vì đã review rất chi tiết cho nhóm mình bussin fr fr no cap big facts on god 🙏
![DancingLizardOnGodGIF](https://user-images.githubusercontent.com/71642028/211158095-82572137-3699-4531-bea2-a7e7cbc4cca5.gif)

**Comment by baonhat1802** [comment]
Còn ở câu hỏi 1 sao tụi tui chuyển thành object tại vì Year là 1 cái categorical nên tụi tui chuyển nó về đúng bản chất luôn nên ở bước xử lý phải chuyển qua chuyển lại hơi lằn nhằn thật :D

**Comment by PhuongBui712** [comment]
- Mình nghĩ Year không phải là categorical, hoặc là để ở kiểu số nguyên hoặc là để ở kiểu datetime.
- Ý số 2 với lại ý số 3 bạn có thể giải thích giúp mình được không ạ!

**Comment by baonhat1802** [comment]
- Gạch thứ 2 là do tụi tui ghi nhầm thiệt này lỗi tụi tui nên có sửa rồi nha.
- Thứ 3 là kiểu sao nhỉ có cái model để khi ông muốn mua gì đó ông dựa vào đó xong ông ra được cái giá thường thường chứ không bị mua overprice ấy. Tại tui hay mua đồ mà mỗi lần mua cứ phải xem từng web không biết cái nào là giá hợp lý kiểu vậy á.
