### ISSUE TITLE
Nhận xét

### ISSUE THREAD

**Issue by namphuong165** [bovip1822002/Project-Programming-DS#5]
Nhóm có phân chia công việc cụ thể. Trình bày đẹp, đầy đủ, khá dễ hiểu. Tuy nhiên nhóm bạn chưa làm phần mục lục và mình nghĩ các bạn nên hạn chế dùng dòng for để code có thể tối ưu hơn.
20127288-Nguyễn Nam Phương

**Comment by baonhat1802** [comment]
Cám ơn lời nhận nhét từ bạn Lam Phương nhé <3
