### ISSUE TITLE
(20127088_Nguyễn Thiện Hoàng Trí) Nhận xét

### ISSUE THREAD

**Issue by hoangsidrpr** [bovip1822002/Project-Programming-DS#6]
Nhóm phân chia dữ liệu hợp lý và sử dụng model để giải quyết câu hỏi một cách hợp lý. Markdown chú thích các phần code dễ hiểu và rõ ràng. Nhóm bạn làm rất ấn tượng trình bày dễ hiểu đặc biệt là phân tích giải quyết 2 câu hỏi. Mặt khác theo mình thì nhóm các bạn cần hạn chế dùng loop để giải quyết các vấn đề thì bài làm sẽ hoàn thiện hơn.

**Comment by nthng-quan** [comment]
test

**Comment by nthng-quan** [comment]
Mặc khác là mặc gì bạn, mặc cảm à ?

**Comment by baonhat1802** [comment]
Ok cám ơn lời nhận xét của Bạn Trí Mập nhé
