### ISSUE TITLE
20127082 - Lâm Thị Xuân Thy

### ISSUE THREAD

**Issue by amandalm18082000** [bovip1822002/Project-Programming-DS#7]
- Đầu tiên mình có nhận xét đôi nét sau đây sau khi xem bài của nhóm bạn dựa trên file bạn up trên github.
- Mình có download all toàn bộ code của bạn về chạy và mình bị failed . Cụ thể mình failed chỗ này:
![image](https://user-images.githubusercontent.com/74856219/211178442-cbfc528e-6857-43c5-a5f0-e7ab1654dc75.png)
- Mình xem trên cái bạn up trên ibynb thì thấy bạn chưa restart all nên mình chỉ xem trên đó thì nhìn chung thấy nhóm bạn có phần tiền xữ lý cẩn thận và hai câu hỏi bạn đặt ra khá hữu ích về phần phân tích.
- Nếu có thể hy vọng bạn có thể modify lại code để mình có thể run được vì lúc ấy mình có thể coi được nhiều hơn nha.

**Comment by baonhat1802** [comment]
À cám ơn bà nhiều nha. Cái đó là của One hot encoding ấy do tụi tui với bà xài môi trường khác nhau nên cái one hot encoder có cái parameter là sparse_output mấy bản trước nó là sparse thôi thì phải nên chạy nó sẽ báo lỗi á chắc thêm tui thêm try except luôn cám ơn bà nhiều nha <3
